// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"メイン画面へ進む前に、\"Made with MV\"のスプラッシュ画面もしくはカスタマイズされたスプラッシュ画面を表示します。","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"TitleCommandPosition","status":false,"description":"タイトルコマンドウィンドウの位置を変更します。","parameters":{"Offset X":"0","Offset Y":"0","Width":"240","Background":"0"}},
{"name":"ParallaxLayerMap","status":true,"description":"多層レイヤー一枚絵マッププラグイン","parameters":{}},
{"name":"MousePointerExtend","status":false,"description":"マウスポインタ拡張プラグイン","parameters":{"形状タイプ1":"crosshair","スイッチ1":"0","形状タイプ2":"auto","スイッチ2":"0","形状タイプ3":"auto","スイッチ3":"0","形状タイプ4":"auto","スイッチ4":"0","形状タイプ5":"auto","スイッチ5":"0","デフォルト形状タイプ":"crosshair","独自画像1":"","独自画像2":"","独自画像3":"","独自画像4":"","独自画像5":"","キー入力で消去":"OFF","ポインタファイルパス":""}},
{"name":"GraphicalDesignMode","status":false,"description":"GUI画面デザインプラグイン\nパラメータを変更したら「プロジェクトの保存」（Ctrl+S）","parameters":{"デザインモード":"true","自動保存":"false","モバイル版作成":"false","モバイル偽装":"false","ウィンドウ透過":"false","グリッドサイズ":"48","パディング":"0","フォントサイズ":"0","行の高さ":"0","背景透明度":"0","アイコンサイズ調整":"false","背景表示可否固定":"false","右クリックで消去":"false"}},
{"name":"Picture_window_riru","status":true,"description":"メッセージウィンドウ表示時、消去時にコモンイベントを起動させて自動ピクチャウィンドウを可能にします","parameters":{"PWnodisplaySwitch":"0","OpenCommon":"0","CloseCommon":"0"}},
{"name":"AdjustPictureGraphical","status":true,"description":"ピクチャのグラフィカルな位置調整プラグイン。\nパラメータを変更したら「プロジェクトの保存」（Ctrl+S）","parameters":{"グリッドサイズ":"48","テストマップID":"-1"}},
{"name":"PictureCallCommon","status":true,"description":"ピクチャのボタン化プラグイン","parameters":{"透明色を考慮":"ON","ピクチャ番号の変数番号":"0","ポインタX座標の変数番号":"0","ポインタY座標の変数番号":"0","タッチ操作抑制":"OFF","戦闘中常にコモン実行":"OFF"}},
{"name":"AB_SymbolEncounter","status":true,"description":"出現位置がランダムなシンボルエンカウントシステム","parameters":{"FindBalloon":"1","LoseBalloon":"2","FindMoveSpeed":"4","NormalMoveSpeed":"3","AppearanceTime":"100","SightArea":"5","WarpTryTime":"10","ChaseArea":"8","AppearanceArea":"15","WarpArea":"10","LoseCount":"100","MinWaitTime":"60","RndWaitTime":"60","SightColor":"red","SightVisibleSwId":"1","SightOpacity":"64","StareCountMin":"180","FollowersThrough":"0"}},
{"name":"RTK_Test","status":true,"description":"Test","parameters":{}},
{"name":"YEP_EventChasePlayer","status":true,"description":"v1.07 When a player is in the proximity of a certain event,\nthe event will start chasing or fleeing from the player.","parameters":{"Sight Lock":"300","See Player":"true","Alert Timer":"120","Alert Balloon":"1","Alert Sound":"Attack1","Alert Common Event":"0","Return After":"true","Return Wait":"180"}},
{"name":"YEP_RegionRestrictions","status":false,"description":"v1.04 Use regions to block out Events and/or the player from\nbeing able to venture into those spots.","parameters":{"Player Restrict":"0","Event Restrict":"0","All Restrict":"2","Player Allow":"0","Event Allow":"0","All Allow":"0"}},
{"name":"MessageWindowHidden","status":false,"description":"メッセージウィンドウ一時消去プラグイン","parameters":{"ボタン名称":"右クリック"}}
];
